apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-ts-app
  labels:
    app: my-node-ts-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-ts-app
  template:
    metadata:
      labels:
        app: my-node-ts-app
    spec:
      containers:
        - name: my-node-ts-app
          image: xil01/my-node-ts-app:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
